chore: CI check main config

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check Environment Variables
+        run: |
+          echo "Checking secrets..."
+          [ -z "$IMAGEKIT_PUBLIC_KEY" ] && echo "IMAGEKIT_PUBLIC_KEY is missing!" || echo "IMAGEKIT_PUBLIC_KEY is set."
+          [ -z "$IMAGEKIT_PRIVATE_KEY" ] && echo "IMAGEKIT_PRIVATE_KEY is missing!" || echo "IMAGEKIT_PRIVATE_KEY is set."
+
       - name: Checkout code
         uses: actions/checkout@v4
         with:
@@ -44,7 +50,6 @@ jobs:
         run: npm run test
         env:
           CI: true
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
           IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
           IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
